title: ASIACOMKHK
description: 热爱技术、乐于解决问题的开发者
baseurl: ""
url: "https://asiacomkhk.github.io"

# GitHub Pages 官方主题（任选一个）
theme: jekyll-theme-cayman

# 如果你想用第三方主题，就用下面这行，注释掉上面 theme
# remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-remote-theme
